apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: kinosoft
    service: backend
spec:
  selector:
    app: kinosoft
    service: backend
  ports:
    - name: standard-port
      port: 80
      targetPort: 8080
    - name: application-port
      port: 8080
      targetPort: 8080
