apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: kinosoft
    service: frontend
spec:
  selector:
    app: kinosoft
    service: frontend
  ports:
    - port: 80
      targetPort: 80